### ISSUE TITLE
Webcord failing to install on Fedora 37 aarch64

### ISSUE THREAD

**Issue by cobalt2727** [dvershinin/lastversion#117]
**Project with incorrect version**

### **_This behavior does not occur on x86_64 Fedora 37, only aarch64._**
When trying to install [Webcord](https://github.com/SpacingBat3/WebCord/) it seems like it's targeting the AppImage, instead of the arm64 RPM like it should.

**To Reproduce**

What command have you run, e.g. `lastversion <project location> --verbose`
Get an aarch64 Fedora 37 environment, then run `sudo lastversion install webcord`. You'll be met with the following:
```python
Traceback (most recent call last):
  File "/usr/bin/lastversion", line 33, in <module>
    sys.exit(load_entry_point('lastversion==3.3.2', 'console_scripts', 'lastversion')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lastversion/lastversion.py", line 591, in main
    return install_app_image(
           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lastversion/lastversion.py", line 374, in install_app_image
    extract_appimage_desktop_file(app_file_name)
  File "/usr/lib/python3.11/site-packages/lastversion/utils.py", line 172, in extract_appimage_desktop_file
    subprocess.call([appimage_path, "--appimage-extract"], cwd=temp_dir)
  File "/usr/lib64/python3.11/subprocess.py", line 389, in call
    with Popen(*popenargs, **kwargs) as p:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib64/python3.11/subprocess.py", line 1950, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/root/Applications/WebCord.AppImage'
```

**Expected behavior**

I would expect it to download the RPM instead of the AppImage

**Program output**

see above

### Support This Project

tempting offer but I am broke

**Comment by cobalt2727** [comment]
Can't think of any other repos that offer both arm64 RPMs and AppImages off the top of my head, but if you've got links to any I can test them, too.

**Comment by dvershinin** [comment]
@cobalt2727 Hi, was `lastversion` itself installed as an RPM package? or via `pip`?

**Comment by cobalt2727** [comment]
RPM (for both x64 and aarch64)

**Comment by cobalt2727** [comment]
Can also confirm it's using the latest version of lastversion, this was tested with a fresh install on a VM.

**Comment by cobalt2727** [comment]
@dvershinin Still happening with the most recent version, unfortunately

**Comment by cobalt2727** [comment]
does that work with the `lastversion install` command, or should I just swap my script back to manually downloading the assets first? either way is fine by me

**Comment by dvershinin** [comment]
Yes it should work with the `install` command.

**Comment by dvershinin** [comment]
This is a valid bug. The issue is in the `install_release` function in `lastversion.py`:

```python
def install_release(res, args):
    app_images = [asset for asset in res["assets"] if asset.endswith(".AppImage")]
    if app_images:
        return install_app_image(app_images[0], ...)  # Picks first AppImage regardless of arch
```

The problem is:
1. AppImages are prioritized over RPMs
2. No architecture filtering is done before selection - it just picks the first `.AppImage` asset

**Proposed fix:**
1. Apply architecture filtering BEFORE selecting an installable asset
2. On Fedora/RHEL, prefer RPM over AppImage when available
3. Use `platform.machine()` to match architecture (aarch64, x86_64, etc.)

Workaround for now:
```bash
lastversion --filter 'arm64.*\.rpm' download SpacingBat3/WebCord
sudo dnf install ./webcord-*.rpm
```

Will work on a proper fix.
