### ISSUE TITLE
Error in docker build linux/arm/v7

### ISSUE THREAD

**Issue by ShoGinn** [dvershinin/lastversion#13]
This is an awesome tool. But I had a problem in my multi-arch docker build.
I cant replicate it outside of travis (cant get qemu to run locally).

the error is this:
```
#51 [linux/arm/v7 builder 4/7] RUN lastversion mutability/mlat-client --down...
1314#51 4.477 Traceback (most recent call last):
1315#51 4.477   File "/usr/local/bin/lastversion", line 8, in <module>
1316#51 4.477     sys.exit(main())
1317#51 4.477   File "/usr/local/lib/python3.8/site-packages/lastversion/lastversion.py", line 430, in main
1318#51 4.477     version = latest(args.repo, args.format, args.pre, args.newer_than, args.filter,
1319#51 4.477   File "/usr/local/lib/python3.8/site-packages/lastversion/lastversion.py", line 256, in latest
1320#51 4.477     the_date = r_commit.json()['committer']['date']
1321#51 4.477 KeyError: 'committer'
```

It works fine for v6 and all other...

Link to the travis fail:
https://travis-ci.com/github/ShoGinn/adsbexchange-mlat/builds/153330515

excerpt from the failed command
```Dockerfile
FROM --platform=$TARGETPLATFORM python as builder


WORKDIR /mlat-client


RUN pip3 install --upgrade shiv importlib-resources lastversion


RUN \
    lastversion mutability/mlat-client --download mlat-client.tar.gz && \
```

**Comment by dvershinin** [comment]
I think you're not using the `GITHUB_API_TOKEN` env var, as per [tips](https://github.com/dvershinin/lastversion#tips).

Despite the effort with caching of GitHub API responses, the tool needs to make a lot of requests to get reliable data. And for many requests, having a token is needed.

Can you try setting `GITHUB_API_TOKEN` ?

To make sure the token is in use, you can run with `lastversion --verbose ...` and then the output should include:

    INFO: Using API token.

**Comment by ShoGinn** [comment]
@dvershinin I made sure I had the ```GITHUB_API_TOKEN```  was incorporated since it was a travis build.

I ran the build 2 times just to make sure.

**Comment by ShoGinn** [comment]
gonna spin up a Debian vm with qemu and see if I can replicate for you ;) pretty unfair for me to give you so little info.

**Comment by ShoGinn** [comment]
I cant get a consistent result.. but I was limiting my token to only certain functions.. which ones are necessary?

I just had:

read:packages

**Comment by ShoGinn** [comment]
You are correct its an API issue, and because its docker its not pulling global env.

I guess there still exists a problem.. here is the dump none the less:

```
#29 [linux/arm/v7 builder 4/7] RUN lastversion mutability/mlat-client --verb...
1784#29 2.738 INFO: Verbose output.
1785#29 2.740 INFO: Using cache directory: /root/.cache/lastversion.
1786#29 2.779 DEBUG: Looking up "https://api.github.com/repos/mutability/mlat-client/releases/latest" in the cache
1787#29 2.782 DEBUG: No cache entry available
1788#29 2.789 DEBUG: Starting new HTTPS connection (1): api.github.com:443
1789#29 3.236 DEBUG: https://api.github.com:443 "GET /repos/mutability/mlat-client/releases/latest HTTP/1.1" 404 None
1790#29 3.251 DEBUG: Status code 404 not in (200, 203, 300, 301)
1791#29 3.264 DEBUG: Looking up "https://api.github.com/repos/mutability/mlat-client/tags?per_page=100" in the cache
1796#29 3.267 DEBUG: No cache entry available
1797#29 3.393 DEBUG: https://api.github.com:443 "GET /repos/mutability/mlat-client/tags?per_page=100 HTTP/1.1" 200 None
1798#29 3.405 DEBUG: Updating cache with response from "https://api.github.com/repos/mutability/mlat-client/tags?per_page=100"
1799#29 3.406 DEBUG: Caching due to etag
1800#29 3.425 INFO: Checking tag v0.2.11 as version.
1801#29 3.428 INFO: Parsed as Version OK
1802#29 3.430 INFO: String representation of version is 0.2.11.
1803#29 3.439 DEBUG: Looking up "https://api.github.com/repos/mutability/mlat-client/git/commits/5dc5bda8af4cf090d4fdc958c43f195da79951d4" in the cache
1804#29 3.441 DEBUG: No cache entry available
1805#29 3.509 DEBUG: https://api.github.com:443 "GET /repos/mutability/mlat-client/git/commits/5dc5bda8af4cf090d4fdc958c43f195da79951d4 HTTP/1.1" 200 None
1806#29 3.522 DEBUG: Updating cache with response from "https://api.github.com/repos/mutability/mlat-client/git/commits/5dc5bda8af4cf090d4fdc958c43f195da79951d4"
1807#29 3.524 DEBUG: Caching due to etag
1808#29 3.552 DEBUG: Looking up "https://api.github.com/repos/mutability/mlat-client/releases/tags/v0.2.11" in the cache
1809#29 3.554 DEBUG: No cache entry available
1810#29 3.634 DEBUG: https://api.github.com:443 "GET /repos/mutability/mlat-client/releases/tags/v0.2.11 HTTP/1.1" 404 None
1811#29 3.645 DEBUG: Status code 404 not in (200, 203, 300, 301)
1812#29 3.648 INFO: Setting version as current selection: 0.2.11.
1813#29 3.649 INFO: Checking tag v0.2.10 as version.
1814#29 3.651 INFO: Parsed as Version OK
1815#29 3.652 INFO: String representation of version is 0.2.10.
1792#29 3.662 DEBUG: Looking up "https://api.github.com/repos/mutability/mlat-client/git/commits/59e3d57ec0772d0dc5d7cde5a02130548a584840" in the cache
1793#29 3.664 DEBUG: No cache entry available
1794#29 3.729 DEBUG: https://api.github.com:443 "GET /repos/mutability/mlat-client/git/commits/59e3d57ec0772d0dc5d7cde5a02130548a584840 HTTP/1.1" 200 None
1795#29 3.738 DEBUG: Updating cache with response from "https://api.github.com/repos/mutability/mlat-client/git/commits/59e3d57ec0772d0dc5d7cde5a02130548a584840"
1816#29 3.743 DEBUG: Caching due to etag
1828#29 3.753 INFO: Checking tag v0.2.9 as version.
1829#29 3.754 INFO: Parsed as Version OK
1830#29 3.756 INFO: String representation of version is 0.2.9.
1831#29 3.765 DEBUG: Looking up "https://api.github.com/repos/mutability/mlat-client/git/commits/3ddaeb1609c4eaeee7a74d19534bc85995b0b43f" in the cache
1832#29 3.766 DEBUG: No cache entry available
1833#29 3.838 DEBUG: https://api.github.com:443 "GET /repos/mutability/mlat-client/git/commits/3ddaeb1609c4eaeee7a74d19534bc85995b0b43f HTTP/1.1" 200 None
1834#29 3.850 DEBUG: Updating cache with response from "https://api.github.com/repos/mutability/mlat-client/git/commits/3ddaeb1609c4eaeee7a74d19534bc85995b0b43f"
1835#29 3.852 DEBUG: Caching due to etag
1836#29 3.862 INFO: Checking tag v0.2.8 as version.
1837#29 3.864 INFO: Parsed as Version OK
1838#29 3.865 INFO: String representation of version is 0.2.8.
1839#29 3.874 DEBUG: Looking up "https://api.github.com/repos/mutability/mlat-client/git/commits/89c18fedb2eaffc0e4807addb6cb65471a4e0379" in the cache
1840#29 3.876 DEBUG: No cache entry available
1841#29 3.954 DEBUG: https://api.github.com:443 "GET /repos/mutability/mlat-client/git/commits/89c18fedb2eaffc0e4807addb6cb65471a4e0379 HTTP/1.1" 200 None
1842#29 3.967 DEBUG: Updating cache with response from "https://api.github.com/repos/mutability/mlat-client/git/commits/89c18fedb2eaffc0e4807addb6cb65471a4e0379"
1843#29 3.969 DEBUG: Caching due to etag
1844#29 3.982 INFO: Checking tag v0.2.7 as version.
1845#29 3.984 INFO: Parsed as Version OK
1846#29 3.985 INFO: String representation of version is 0.2.7.
1847#29 3.995 DEBUG: Looking up "https://api.github.com/repos/mutability/mlat-client/git/commits/43c13f07e9cc7d2b65626938363e1f420b69dbba" in the cache
1817#29 3.997 DEBUG: No cache entry available
1818#29 4.083 DEBUG: https://api.github.com:443 "GET /repos/mutability/mlat-client/git/commits/43c13f07e9cc7d2b65626938363e1f420b69dbba HTTP/1.1" 200 None
1819#29 4.097 DEBUG: Updating cache with response from "https://api.github.com/repos/mutability/mlat-client/git/commits/43c13f07e9cc7d2b65626938363e1f420b69dbba"
1820#29 4.098 DEBUG: Caching due to etag
1821#29 4.109 INFO: Checking tag v0.2.6 as version.
1822#29 4.111 INFO: Parsed as Version OK
1823#29 4.112 INFO: String representation of version is 0.2.6.
1824#29 4.121 DEBUG: Looking up "https://api.github.com/repos/mutability/mlat-client/git/commits/84c8c8a2ac2b74a175f825f3798b31ea5429f6c9" in the cache
1825#29 4.123 DEBUG: No cache entry available
1826#29 4.180 DEBUG: https://api.github.com:443 "GET /repos/mutability/mlat-client/git/commits/84c8c8a2ac2b74a175f825f3798b31ea5429f6c9 HTTP/1.1" 403 None
1827#29 4.188 DEBUG: Status code 403 not in (200, 203, 300, 301)
1848#29 4.221 Traceback (most recent call last):
1852#29 4.221   File "/usr/local/bin/lastversion", line 8, in <module>
1853#29 4.221     sys.exit(main())
1854#29 4.221   File "/usr/local/lib/python3.8/site-packages/lastversion/lastversion.py", line 430, in main
1855#29 4.221     version = latest(args.repo, args.format, args.pre, args.newer_than, args.filter,
1856#29 4.221   File "/usr/local/lib/python3.8/site-packages/lastversion/lastversion.py", line 256, in latest
1857#29 4.221     the_date = r_commit.json()['committer']['date']
1858#29 4.221 KeyError: 'committer'
```

**Comment by dvershinin** [comment]
I think you're looking for `public_repo` permission which is listed as `Access public repositories`.
That probably would also need to be coupled with `repo:status`, like this:

![image](https://user-images.githubusercontent.com/250071/76693197-42213980-6672-11ea-898a-1ff987600316.png)

Although I'm not really sure which correspond to which actual API endpoints.

But the issue really is that there should be a more graceful way to show that 403 API error as requiring a token or a token permission is missing (instead of the exception) :)

**Comment by dvershinin** [comment]
Looking again at the last build log, the token is not used at all, so I think you need to pass it somehow more explicitly to the docker build.

**Comment by ShoGinn** [comment]
Spot on. It won’t error with the token. Docker problem is part. 

But I think the error should be captured. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dvershinin** [comment]
@ShoGinn the error should be captured in the new release. 

In fact, it will also emit a warning in case
of the rate limit being exceeded, and wait for it to be recharged... An edge case, untested, but hopefully works, as this would improve reliability a lot..
