### ISSUE TITLE
 'HTTPResponse' object has no attribute 'chunked'

### ISSUE THREAD

**Issue by mbunkin** [dvershinin/lastversion#18]
Installed using pip

lastversion https://github.com/php/php-src

Traceback (most recent call last):
  File "/usr/bin/lastversion", line 9, in <module>
    load_entry_point('lastversion==1.1.1', 'console_scripts', 'lastversion')()
  File "/usr/lib/python2.7/site-packages/lastversion/lastversion.py", line 195, in main
    args.shorter_urls, args.major)
  File "/usr/lib/python2.7/site-packages/lastversion/lastversion.py", line 53, in latest
    release = s.get_latest(pre_ok=pre_ok, major=major)
  File "/usr/lib/python2.7/site-packages/lastversion/GitHubRepoSession.py", line 137, in get_latest
    r = self.get('https://{}/{}/releases.atom'.format(self.hostname, self.repo))
  File "/usr/lib/python2.7/site-packages/lastversion/GitHubRepoSession.py", line 46, in get
    r = super(GitHubRepoSession, self).get(url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 498, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 486, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 598, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib64/python2.7/site-packages/cachecontrol/adapter.py", line 53, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 437, in send
    return self.build_response(request, resp)
  File "/usr/lib64/python2.7/site-packages/cachecontrol/adapter.py", line 107, in build_response
    if response.chunked:
AttributeError: 'HTTPResponse' object has no attribute 'chunked'

**Comment by dvershinin** [comment]
@mbunkin this happens due to cachecontrol's [issue](https://github.com/ionrock/cachecontrol/issues/137). 
Likely you `requests` Python package is too old.

Unfortunately, they have not merged the pull request with the trivial fix. 

The best way to go around lastversion is either using the packaged install (if you're on CentOS/RHEL) or pip in a virtualenv.

**Comment by mbunkin** [comment]
Thank you! But I thought pip is a package manager, why doesn't it check for the requests package version when installing lastversion?

**Comment by dvershinin** [comment]
There was no specific version requirement set by lastversion, so `pip` was satisfied with whatever `requests` package you already had before. The new version of lastversion will set the requirement to be more explicit.
