### ISSUE TITLE
exception when trying to fetch version of mozilla/rhino

### ISSUE THREAD

**Issue by IlanBeloglovsky** [dvershinin/lastversion#42]
I try to fetch the version of mozilla/rhino.
Thats how i run the command"
`lastversion mozilla/rhino`
and i get the following error:
```Traceback (most recent call last):
  File "c:\users\ilan beloglovsky\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\ilan beloglovsky\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Ilan Beloglovsky\AppData\Local\Programs\Python\Python37\Scripts\lastversion.exe\__main__.py", line 7, in <module>
  File "c:\users\ilan beloglovsky\appdata\local\programs\python\python37\lib\site-packages\lastversion\lastversion.py", line 253, in main
    args.shorter_urls, args.major, args.only)
  File "c:\users\ilan beloglovsky\appdata\local\programs\python\python37\lib\site-packages\lastversion\lastversion.py", line 53, in latest
    release = s.get_latest(pre_ok=pre_ok, major=major)
  File "c:\users\ilan beloglovsky\appdata\local\programs\python\python37\lib\site-packages\lastversion\GitHubRepoSession.py", line 464, in get_latest
    ret = self.find_in_tags_via_graphql(ret, pre_ok, major)
  File "c:\users\ilan beloglovsky\appdata\local\programs\python\python37\lib\site-packages\lastversion\GitHubRepoSession.py", line 255, in find_in_tags_via_graphql
    d = node['target']['tagger']['date']
KeyError: 'tagger'
```

I use
 `lastversion==1.3.1`
`windows 10 Pro==20H2`

**Comment by dvershinin** [comment]
Thanks a bunch for reporting this. Been fixed in v1.3.2
