### ISSUE TITLE
python3 version of lastversion for CentOS/RHEL 7, 8

### ISSUE THREAD

**Issue by rungitta** [dvershinin/lastversion#52]
Installing `lastversion` on rhel7 it seems like it's installed with python2. Can you make it so it's installed with python3?

```bash
Installed:
  lastversion.noarch 0:1.4.0-1.el7

Dependency Installed:
  python-feedparser.noarch 0:5.1.3-3.el7         python-requests.noarch 0:2.6.0-10.el7 python2-CacheControl.noarch 0:0.12.6-3.el7 python2-appdirs.noarch 0:1.4.4-1.el7
  python2-beautifulsoup4.noarch 0:4.6.3-2.el7sat python2-distro.noarch 0:1.2.0-3.el7   python2-lastversion.noarch 0:1.4.0-1.el7   python2-lockfile.noarch 1:0.11.0-17.el7
  python2-msgpack.x86_64 0:0.5.6-5.el7           python2-packaging.noarch 0:16.8-6.el7 python2-six.noarch 0:1.9.0-0.el7           python2-tqdm.noarch 0:4.50.2-1.el7

Failed:
  python-urllib3.noarch 0:1.10.2-7.el7
```

Then I get this error:

```bash
$ lastversion --version
Traceback (most recent call last):
  File "/usr/bin/lastversion", line 9, in <module>
    load_entry_point('lastversion==1.4.0', 'console_scripts', 'lastversion')()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 378, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2566, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2260, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/lib/python2.7/site-packages/lastversion/__init__.py", line 14, in <module>
    from .lastversion import __self__
  File "/usr/lib/python2.7/site-packages/lastversion/lastversion.py", line 22, in <module>
    from cachecontrol import CacheControl
  File "/usr/lib/python2.7/site-packages/cachecontrol/__init__.py", line 9, in <module>
    from .wrapper import CacheControl
  File "/usr/lib/python2.7/site-packages/cachecontrol/wrapper.py", line 1, in <module>
    from .adapter import CacheControlAdapter
  File "/usr/lib/python2.7/site-packages/cachecontrol/adapter.py", line 5, in <module>
    from requests.adapters import HTTPAdapter
  File "/usr/lib/python2.7/site-packages/requests/__init__.py", line 58, in <module>
    from . import utils
  File "/usr/lib/python2.7/site-packages/requests/utils.py", line 32, in <module>
    from .exceptions import InvalidURL
  File "/usr/lib/python2.7/site-packages/requests/exceptions.py", line 10, in <module>
    from urllib3.exceptions import HTTPError as BaseHTTPError
  File "/usr/lib/python2.7/site-packages/urllib3/__init__.py", line 10, in <module>
    from .connectionpool import (
  File "/usr/lib/python2.7/site-packages/urllib3/connectionpool.py", line 31, in <module>
    from .connection import (
  File "/usr/lib/python2.7/site-packages/urllib3/connection.py", line 45, in <module>
    from .util.ssl_ import (
  File "/usr/lib/python2.7/site-packages/urllib3/util/__init__.py", line 4, in <module>
    from .request import make_headers
  File "/usr/lib/python2.7/site-packages/urllib3/util/request.py", line 5, in <module>
    from ..exceptions import UnrewindableBodyError
ImportError: cannot import name UnrewindableBodyError
```

**Comment by dvershinin** [comment]
Note this in your output:

> Failed:
>   python-urllib3.noarch 0:1.10.2-7.el7

It appears that the dependency package failed to install. Reinstall it, and things should work as they should:

```bash
yum reinstall python-urllib3
```
Regarding Python 3 package of `lastversion` for CentOS 7. Probably not as of yet. It is based on the default Python interpreter on that OS, to reduce the number of dependencies...

**Comment by rungitta** [comment]
Hmm.. I installed `python-urllib3` but now get this error:

```bash
$ lastversion
Traceback (most recent call last):
  File "/usr/bin/lastversion", line 9, in <module>
    load_entry_point('lastversion==1.4.0', 'console_scripts', 'lastversion')()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 378, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2566, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2260, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/lib/python2.7/site-packages/lastversion/__init__.py", line 14, in <module>
    from .lastversion import __self__
  File "/usr/lib/python2.7/site-packages/lastversion/lastversion.py", line 22, in <module>
    from cachecontrol import CacheControl
  File "/usr/lib/python2.7/site-packages/cachecontrol/__init__.py", line 9, in <module>
    from .wrapper import CacheControl
  File "/usr/lib/python2.7/site-packages/cachecontrol/wrapper.py", line 1, in <module>
    from .adapter import CacheControlAdapter
  File "/usr/lib/python2.7/site-packages/cachecontrol/adapter.py", line 5, in <module>
    from requests.adapters import HTTPAdapter
  File "/usr/lib/python2.7/site-packages/requests/__init__.py", line 58, in <module>
    from . import utils
  File "/usr/lib/python2.7/site-packages/requests/utils.py", line 32, in <module>
    from .exceptions import InvalidURL
  File "/usr/lib/python2.7/site-packages/requests/exceptions.py", line 10, in <module>
    from urllib3.exceptions import HTTPError as BaseHTTPError
  File "/usr/lib/python2.7/site-packages/urllib3/__init__.py", line 10, in <module>
    from .connectionpool import (
  File "/usr/lib/python2.7/site-packages/urllib3/connectionpool.py", line 31, in <module>
    from .connection import (
  File "/usr/lib/python2.7/site-packages/urllib3/connection.py", line 45, in <module>
    from .util.ssl_ import (
  File "/usr/lib/python2.7/site-packages/urllib3/util/__init__.py", line 4, in <module>
    from .request import make_headers
  File "/usr/lib/python2.7/site-packages/urllib3/util/request.py", line 5, in <module>
    from ..exceptions import UnrewindableBodyError
ImportError: cannot import name UnrewindableBodyError
```

**Comment by dvershinin** [comment]
It doesn’t seem that the error has changed even a bit. Sure to have *re*installed the mentioned package? (Not just installed). 

Check disk usage. I wonder why it failed to install in the first place. 

Also might be that you have used pip manually and have conflicting files either in users .local directory or globally.

**Comment by rungitta** [comment]
Disk no problem. Removed $HOME/.local. Reinstalled and seem to be an issue with the version of urllib3:

```bash
Reinstalling:
 python-urllib3                            noarch                            1.10.2-7.el7                               rhel-7-server-rpms                            103 k
```

```bash
$ lastversion
Traceback (most recent call last):
  File "/usr/bin/lastversion", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 3011, in <module>
    parse_requirements(__requires__), Environment()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 626, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: urllib3>=1.21.1,!=1.25.0,!=1.25.1,<1.26
```

**Comment by dvershinin** [comment]
I have the exact same `python-urllib3` package, and things work fine.

Your issue stems from the previous failure to install it, or other misconfiguration on the machine.

The fact that it "Failed:" to install initially might indicate a corrupted disk or other problems. 
If it were a network error while downloading the package, then `yum` would bail before proceeding with the transaction.

However, in your case, it went on to process the transaction after successfully downloading all the packages.

Does `/usr/lib/python2.7/site-packages/urllib3-1.10.2-py2.7.egg-info/PKG-INFO` exist?

**Comment by rungitta** [comment]
yes, that file exists.

**Comment by dvershinin** [comment]
Closing as nothing really to do about it. Please try on a clean CentOS 7 system.
As far as CentOS/RHEL 8, lastversion links against Python 3 on those systems.

**Comment by dvershinin** [comment]
FYI, the Python 3 app is now the default on CentOS 7.
